{% set name = "rsspolymlp" %}
{% set version = "0.2.8" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36445752eec9a218977c12fa32fa572beb5cc5b0de393a018e4cf536dd7cfc6c

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vv
  number: 0
  entry_points:
    - rsspolymlp = rsspolymlp.api.cli_rsspolymlp:run
    - rsspolymlp-devkit = rsspolymlp.api.cli_rsspolymlp_devkit:run
    - rsspolymlp-plot = rsspolymlp.api.cli_rsspolymlp_plot:run

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - joblib
    - pypolymlp
    - spglib
    - symfc

test:
  imports:
    - rsspolymlp

  requires:
    - python {{ python_min }}
    - pip
    - matplotlib
    - seaborn

  commands:
    - rsspolymlp --help
    - rsspolymlp-devkit --help
    - rsspolymlp-plot --help
    - pip check

about:
  home: https://github.com/hytwakai/rsspolymlp
  license: MIT
  license_file: LICENSE
  summary: A framework for random structure search using polynomial MLPs

extra:
  recipe-maintainers:
    - hytwakai
