{% set name = "rsspolymlp" %}
{% set version = "0.0.13" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dc0ed9204c8c25d2bd4405fd32bced9093eb87ce116a66dc347a0466de26952

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vv
  number: 0
  entry_points:
    - rss-init-struct = rsspolymlp.api.cli_rss:run_rss_init_struct
    - rss-parallel = rsspolymlp.api.cli_rss:run_rss_parallel
    - rss-single-srun = rsspolymlp.api.cli_rss:run_rss_single_srun
    - rss-uniq-struct = rsspolymlp.api.cli_rss:run_rss_uniq_struct
    - rss-summarize = rsspolymlp.api.cli_rss:run_rss_summarize
    - rss-ghost-minima = rsspolymlp.api.cli_rss:run_rss_ghost_minima
    - rss-phase-analysis = rsspolymlp.api.cli_rss:run_rss_phase_analysis
    - plot-binary = rsspolymlp.api.cli_plot:run_plot_binary

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - joblib
    - pypolymlp
    - spglib
    - symfc

test:
  imports:
    - rsspolymlp

  requires:
    - python {{ python_min }}
    - pip
    - matplotlib
    - seaborn

  commands:
    - rss-init-struct --help
    - rss-single-srun --help
    - rss-parallel --help
    - rss-uniq-struct --help
    - rss-summarize --help
    - rss-ghost-minima --help
    - rss-phase-analysis --help
    - plot-binary --help
    - pip check

about:
  home: https://github.com/hytwakai/rsspolymlp
  license: MIT
  license_file: LICENSE
  summary: A framework for random structure search using polynomial MLPs

extra:
  recipe-maintainers:
    - hytwakai
