{% set name = "rsspolymlp" %}
{% set version = "0.0.8" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9176c9469b7c77eaad25a09f662d6b21659c595f151682f0364878ac697ef32a

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vv
  number: 0
  entry_points:
    - rss-init-struct = rsspolymlp.rss.random_struct:run
    - rss-single-srun = rsspolymlp.rss.rss_parallel:run_single_srun
    - rss-parallel = rsspolymlp.rss.rss_parallel:run
    - rss-uniq-struct = rsspolymlp.rss.rss_uniq_struct:run
    - rss-summarize = rsspolymlp.analysis.rss_summarize:run
    - rss-outlier = rsspolymlp.analysis.outlier_cands:run
    - rss-outlier-detect = rsspolymlp.analysis.outlier_cands:run_compare_dft
    - plot-binary = rsspolymlp.analysis.plot.binary:run

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pypolymlp
    - symfc
    - spglib
    - joblib

test:
  imports:
    - rsspolymlp

  requires:
    - python {{ python_min }}
    - pip
    - matplotlib
    - seaborn

  commands:
    - rss-init-struct --help
    - rss-single-srun --help
    - rss-parallel --help
    - rss-uniq-struct --help
    - rss-summarize --help
    - rss-outlier --help
    - rss-outlier-detect --help
    - plot-binary --help
    - pip check

about:
  home: https://github.com/hytwakai/rsspolymlp
  license: MIT
  license_file: LICENSE
  summary: A framework for random structure search using polynomial MLPs

extra:
  recipe-maintainers:
    - hytwakai
