{% set name = "rsspolymlp" %}
{% set version = "0.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36e4d1794084d5647681eb895f6612c0dc8db8ed0827a35ba2ef4e01c4f91786

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vv
  number: 0
  entry_points:
    - rsspolymlp = rsspolymlp.api.cli_rsspolymlp:run
    - rsspolymlp-devkit = rsspolymlp.api.cli_rsspolymlp_devkit:run
    - rsspolymlp-plot = rsspolymlp.api.cli_rsspolymlp_plot:run

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - joblib
    - pypolymlp >=0.15
    - spglib
    - symfc

test:
  imports:
    - rsspolymlp

  requires:
    - python {{ python_min }}
    - pip
    - matplotlib
    - seaborn

  commands:
    - rsspolymlp --help
    - rsspolymlp-devkit --help
    - rsspolymlp-plot --help
    - pip check

about:
  home: https://github.com/hytwakai/rsspolymlp
  license: MIT
  license_file: LICENSE
  summary: A framework for random structure search using polynomial MLPs

extra:
  recipe-maintainers:
    - hytwakai
